import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#00346f",
        "primary-container": "#004a99",
        "primary-fixed": "#d7e2ff",
        "primary-fixed-dim": "#abc7ff",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#001b3f",
        "on-primary-fixed-variant": "#00458f",
        "on-primary-container": "#9bbdff",
        secondary: "#046b5e",
        "secondary-container": "#9defde",
        "secondary-fixed": "#a0f2e1",
        "secondary-fixed-dim": "#84d5c5",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#00201b",
        "on-secondary-fixed-variant": "#005046",
        "on-secondary-container": "#0f6f62",
        tertiary: "#003f0b",
        "tertiary-container": "#005914",
        "tertiary-fixed": "#a3f69c",
        "tertiary-fixed-dim": "#88d982",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#002204",
        "on-tertiary-fixed-variant": "#005312",
        "on-tertiary-container": "#7ecf79",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        surface: "#f7f9fb",
        "surface-dim": "#d8dadc",
        "surface-bright": "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "surface-container": "#eceef0",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "surface-variant": "#e0e3e5",
        "surface-tint": "#255dad",
        "on-surface": "#191c1e",
        "on-surface-variant": "#424751",
        "on-background": "#191c1e",
        background: "#f7f9fb",
        outline: "#737783",
        "outline-variant": "#c2c6d3",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        "inverse-primary": "#abc7ff",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      boxShadow: {
        clinical: "0 20px 40px rgba(0, 27, 63, 0.06)",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};

export default config;
